language: cpp
compiler: clang
sudo: false
dist: trusty

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - gcov --version
  - llvm-cov --version

script:
  - ./build.sh
  - ./Debug/selftest

after_success:
  - bash <(curl -s https://codecov.io/bash) -x llvm-cov
